import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer/Footer";
import { FooterNav } from "../components/footerNav/FooterNav";
import Header from "../components/header/Header";
import styles from "./pages.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.index}>
        <Header />
        <Footer />
        <FooterNav />
      </div>
    </div>
  );
};

export default Home;
